"""
===============================================================================
COSMOS Trend Agent Models

Internal models used by the Trend Agent.

Author: COSMOS Development Team
License: MIT
===============================================================================
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from ai.models import SwingPoint


# =============================================================================
# STRUCTURE
# =============================================================================


class StructureType(str, Enum):
    """
    Dow Theory market structure classification.
    """

    HH = "HIGHER_HIGH"
    HL = "HIGHER_LOW"
    LH = "LOWER_HIGH"
    LL = "LOWER_LOW"


# =============================================================================
# TREND REGIME
# =============================================================================


class TrendRegime(str, Enum):
    """
    Current trend regime.
    """

    STRONG_BULLISH = "STRONG_BULLISH"
    BULLISH = "BULLISH"

    SIDEWAYS = "SIDEWAYS"

    BEARISH = "BEARISH"
    STRONG_BEARISH = "STRONG_BEARISH"

    TRANSITION = "TRANSITION"
    UNKNOWN = "UNKNOWN"


# =============================================================================
# TREND EVIDENCE TYPE
# =============================================================================


class TrendEvidenceType(str, Enum):
    """
    Evidence produced by the Trend Agent.

    These values are intentionally chart-oriented so the frontend
    can later render the analysis without knowing internal engine logic.
    """

    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"

    HIGHER_HIGH = "HIGHER_HIGH"
    HIGHER_LOW = "HIGHER_LOW"
    LOWER_HIGH = "LOWER_HIGH"
    LOWER_LOW = "LOWER_LOW"

    SUPPORT = "SUPPORT"
    RESISTANCE = "RESISTANCE"

    TRENDLINE_SUPPORT = "TRENDLINE_SUPPORT"
    TRENDLINE_RESISTANCE = "TRENDLINE_RESISTANCE"

    TRENDLINE_BREAKOUT = "TRENDLINE_BREAKOUT"
    TRENDLINE_BREAKDOWN = "TRENDLINE_BREAKDOWN"

    EMA_ALIGNMENT = "EMA_ALIGNMENT"
    EMA_COMPRESSION = "EMA_COMPRESSION"
    EMA_EXPANSION = "EMA_EXPANSION"

    MOMENTUM_EXPANSION = "MOMENTUM_EXPANSION"
    MOMENTUM_CONTRACTION = "MOMENTUM_CONTRACTION"
    MOMENTUM_EXHAUSTION = "MOMENTUM_EXHAUSTION"

    TREND_CONFIRMATION = "TREND_CONFIRMATION"
    TREND_TRANSITION = "TREND_TRANSITION"


# =============================================================================
# EVIDENCE STATE
# =============================================================================


class EvidenceState(str, Enum):
    """
    Lifecycle state of a piece of trend evidence.
    """

    DEVELOPING = "DEVELOPING"
    CONFIRMED = "CONFIRMED"
    LOCKED = "LOCKED"
    INVALIDATED = "INVALIDATED"


# =============================================================================
# CHART EVIDENCE
# =============================================================================


@dataclass(slots=True)
class TrendEvidence:
    """
    Structured evidence generated by the Trend Agent.

    This is deliberately independent from the frontend. The frontend
    can convert this object into a chart annotation/overlay.
    """

    evidence_type: TrendEvidenceType

    state: EvidenceState = EvidenceState.DEVELOPING

    confidence: float = 0.0

    start_index: int | None = None

    end_index: int | None = None

    start_price: float | None = None

    end_price: float | None = None

    start_timestamp: object | None = None

    end_timestamp: object | None = None

    direction: str | None = None

    label: str | None = None

    reason: str | None = None

    source: str = "trend"

    locked: bool = False


# =============================================================================
# TREND STRUCTURE
# =============================================================================


@dataclass(slots=True)
class TrendStructure:
    """
    Represents the current market structure.
    """

    highs: list[SwingPoint]

    lows: list[SwingPoint]

    structure: list[StructureType]

    bias: str = "NEUTRAL"

    confidence: float = 0.0

    last_structure: StructureType | None = None

    evidence: list[TrendEvidence] = field(
        default_factory=list
    )


# =============================================================================
# TREND SCORE
# =============================================================================


@dataclass(slots=True)
class TrendScore:
    """
    Internal confidence scoring.

    Each component remains independently inspectable so the final
    confidence can be explained and audited.
    """

    structure_score: float = 0.0

    momentum_score: float = 0.0

    ema_score: float = 0.0

    trendline_score: float = 0.0

    total_score: float = 0.0

    confluence_score: float = 0.0

    penalty_score: float = 0.0

    quality_score: float = 0.0

    sample_size: int = 0

    def calculate_total(self) -> float:
        """
        Calculate normalized total score.

        The individual engine scores are expected to be in the
        0-100 range.
        """

        weighted = (
            self.structure_score * 0.30
            + self.momentum_score * 0.25
            + self.ema_score * 0.20
            + self.trendline_score * 0.15
            + self.confluence_score * 0.10
        )

        weighted -= self.penalty_score

        self.total_score = max(
            0.0,
            min(
                100.0,
                weighted,
            ),
        )

        return self.total_score


# =============================================================================
# TREND SNAPSHOT
# =============================================================================


@dataclass(slots=True)
class TrendSnapshot:
    """
    Immutable-style snapshot of the Trend Agent's current conclusion.

    Downstream agents can consume this without needing to understand
    individual Trend engines.
    """

    regime: TrendRegime = TrendRegime.UNKNOWN

    bias: str = "NEUTRAL"

    confidence: float = 0.0

    strength: float = 0.0

    momentum: float = 0.0

    acceleration: bool = False

    structure: list[StructureType] = field(
        default_factory=list
    )

    evidence: list[TrendEvidence] = field(
        default_factory=list
    )

    locked: bool = False