"""
===============================================================================
COSMOS Sell Side Liquidity Engine

Advanced Institutional Sell Side Liquidity Detection.

Responsibilities:
    • Detect Sell Side Liquidity
    • Detect Equal Lows
    • Group nearby swing lows
    • Calculate liquidity strength
    • Calculate liquidity confidence
    • Calculate liquidity age
    • Measure price dispersion
    • Generate explainable evidence
    • Prevent duplicate liquidity levels
    • Rank liquidity by institutional significance
    • Produce deterministic LiquidityObject instances

Author: COSMOS Development Team
License: MIT
Version: 2.0.0
===============================================================================
"""

from __future__ import annotations

from ai.models import SwingPoint
from ai.models import SwingType

from ai.agents.liquidity.constants import (
    LIQUIDITY_TOLERANCE,
    MIN_TOUCHES,
    MAX_AGE,
    MAX_TOUCHES,
)

from ai.agents.liquidity.models import (
    LiquidityObject,
    LiquidityStatus,
    LiquidityType,
)


# =============================================================================
# ENGINE
# =============================================================================


class SellSideEngine:
    """
    Advanced Sell Side Liquidity Engine.

    Sell Side Liquidity generally forms below groups of
    closely aligned swing lows.

    Detection pipeline:

        Swing Lows
            ↓
        Price Grouping
            ↓
        Equal Low Validation
            ↓
        Touch Analysis
            ↓
        Strength Calculation
            ↓
        Confidence Calculation
            ↓
        Age Calculation
            ↓
        Evidence Generation
            ↓
        LiquidityObject
    """

    ENGINE_NAME = "sell_side"

    ENGINE_VERSION = "2.0.0"

    LIQUIDITY_SOURCE = "equal_lows"

    # =========================================================================
    # PUBLIC API
    # =========================================================================

    def analyze(
        self,
        swings: list[SwingPoint],
    ) -> list[LiquidityObject]:
        """
        Analyze swing points and detect Sell Side Liquidity.

        Parameters
        ----------
        swings:
            Swing points generated by the Market Structure Agent.

        Returns
        -------
        list[LiquidityObject]
            Detected Sell Side Liquidity levels.
        """

        if not swings:
            return []

        # ---------------------------------------------------------------------
        # Extract swing lows.
        # ---------------------------------------------------------------------

        lows = self._extract_lows(
            swings
        )

        if len(lows) < MIN_TOUCHES:
            return []

        # ---------------------------------------------------------------------
        # Group equal / near-equal lows.
        # ---------------------------------------------------------------------

        groups = self._group_lows(
            lows
        )

        if not groups:
            return []

        # ---------------------------------------------------------------------
        # Latest swing index is used for age calculation.
        # ---------------------------------------------------------------------

        latest_index = max(
            swing.index
            for swing in swings
        )

        liquidity: list[LiquidityObject] = []

        # ---------------------------------------------------------------------
        # Convert every valid group into one liquidity object.
        # ---------------------------------------------------------------------

        for group in groups:

            level = self._create_liquidity(
                group=group,
                latest_index=latest_index,
            )

            liquidity.append(
                level
            )

        # ---------------------------------------------------------------------
        # Remove accidental duplicates.
        # ---------------------------------------------------------------------

        liquidity = self._deduplicate(
            liquidity
        )

        # ---------------------------------------------------------------------
        # Strongest institutional levels first.
        # ---------------------------------------------------------------------

        liquidity.sort(
            key=lambda level: (
                level.quality,
                level.confidence,
                level.strength,
                level.touches,
            ),
            reverse=True,
        )

        return liquidity

    # =========================================================================
    # SWING EXTRACTION
    # =========================================================================

    def _extract_lows(
        self,
        swings: list[SwingPoint],
    ) -> list[SwingPoint]:
        """
        Extract and deterministically sort swing lows.
        """

        return sorted(
            (
                swing
                for swing in swings
                if swing.swing_type == SwingType.LOW
            ),
            key=lambda swing: (
                swing.price,
                swing.index,
            ),
        )

    # =========================================================================
    # GROUPING
    # =========================================================================

    def _group_lows(
        self,
        lows: list[SwingPoint],
    ) -> list[list[SwingPoint]]:
        """
        Group swing lows that fall within the configured
        liquidity tolerance.
        """

        if not lows:
            return []

        groups: list[list[SwingPoint]] = []

        current_group: list[SwingPoint] = [
            lows[0]
        ]

        for swing in lows[1:]:

            reference = current_group[-1]

            distance = abs(
                swing.price
                - reference.price
            )

            if distance <= LIQUIDITY_TOLERANCE:

                current_group.append(
                    swing
                )

                continue

            if len(current_group) >= MIN_TOUCHES:

                groups.append(
                    current_group
                )

            current_group = [
                swing
            ]

        # ---------------------------------------------------------------------
        # Flush final group.
        # ---------------------------------------------------------------------

        if len(current_group) >= MIN_TOUCHES:

            groups.append(
                current_group
            )

        return groups

    # =========================================================================
    # LIQUIDITY CREATION
    # =========================================================================

    def _create_liquidity(
        self,
        group: list[SwingPoint],
        latest_index: int,
    ) -> LiquidityObject:
        """
        Convert an equal-low group into a LiquidityObject.
        """

        raw_touches = len(
            group
        )

        touches = min(
            raw_touches,
            MAX_TOUCHES,
        )

        # ---------------------------------------------------------------------
        # Representative price.
        #
        # The average provides a stable representation of the
        # equal-low liquidity pool.
        # ---------------------------------------------------------------------

        representative_price = (
            sum(
                swing.price
                for swing in group
            )
            / raw_touches
        )

        representative_price = round(
            representative_price,
            10,
        )

        # ---------------------------------------------------------------------
        # Price dispersion.
        #
        # Smaller dispersion means cleaner equal-low formation.
        # ---------------------------------------------------------------------

        dispersion = self._calculate_dispersion(
            group,
            representative_price,
        )

        # ---------------------------------------------------------------------
        # Strength.
        # ---------------------------------------------------------------------

        strength = self._calculate_strength(
            touches=touches,
            dispersion=dispersion,
        )

        # ---------------------------------------------------------------------
        # Confidence.
        # ---------------------------------------------------------------------

        confidence = self._calculate_confidence(
            touches=touches,
            dispersion=dispersion,
        )

        # ---------------------------------------------------------------------
        # Age.
        # ---------------------------------------------------------------------

        newest_index = max(
            swing.index
            for swing in group
        )

        age = max(
            latest_index
            - newest_index,
            0,
        )

        age = min(
            age,
            MAX_AGE,
        )

        # ---------------------------------------------------------------------
        # Evidence.
        # ---------------------------------------------------------------------

        evidence = self._build_evidence(
            group=group,
            touches=touches,
            price=representative_price,
            dispersion=dispersion,
        )

        # ---------------------------------------------------------------------
        # Create final object.
        # ---------------------------------------------------------------------

        return LiquidityObject(
            liquidity_type=LiquidityType.SELL_SIDE,

            status=LiquidityStatus.UNTOUCHED,

            price=representative_price,

            touches=touches,

            strength=strength,

            confidence=confidence,

            quality=0.0,

            age=age,

            distance=0.0,

            source=self.LIQUIDITY_SOURCE,

            evidence=evidence,
        )

    # =========================================================================
    # DISPERSION
    # =========================================================================

    def _calculate_dispersion(
        self,
        group: list[SwingPoint],
        representative_price: float,
    ) -> float:
        """
        Calculate average absolute price deviation.

        Smaller dispersion means a cleaner equal-low pool.
        """

        if not group:
            return 0.0

        dispersion = sum(
            abs(
                swing.price
                - representative_price
            )
            for swing in group
        ) / len(group)

        return round(
            dispersion,
            10,
        )

    # =========================================================================
    # STRENGTH
    # =========================================================================

    def _calculate_strength(
        self,
        touches: int,
        dispersion: float,
    ) -> float:
        """
        Calculate Sell Side Liquidity strength.

        Touch count is the primary component.
        Price alignment provides a secondary quality adjustment.
        """

        base_strength = min(
            touches * 20,
            100,
        )

        # ---------------------------------------------------------------------
        # Alignment factor.
        # ---------------------------------------------------------------------

        if LIQUIDITY_TOLERANCE <= 0:

            alignment_factor = 1.0

        else:

            alignment_factor = max(
                0.0,
                1.0
                - (
                    dispersion
                    / LIQUIDITY_TOLERANCE
                ),
            )

        adjusted_strength = (
            base_strength
            * (
                0.85
                + (
                    alignment_factor
                    * 0.15
                )
            )
        )

        return round(
            min(
                adjusted_strength,
                100.0,
            ),
            2,
        )

    # =========================================================================
    # CONFIDENCE
    # =========================================================================

    def _calculate_confidence(
        self,
        touches: int,
        dispersion: float,
    ) -> float:
        """
        Calculate detection confidence.

        Confidence increases with:
            • More touches
            • Better price alignment
        """

        base_confidence = min(
            60
            + (
                touches
                * 10
            ),
            100,
        )

        if LIQUIDITY_TOLERANCE <= 0:

            alignment_bonus = 0.0

        else:

            alignment_ratio = max(
                0.0,
                min(
                    1.0,
                    1.0
                    - (
                        dispersion
                        / LIQUIDITY_TOLERANCE
                    ),
                ),
            )

            alignment_bonus = (
                alignment_ratio
                * 10.0
            )

        return round(
            min(
                base_confidence
                + alignment_bonus,
                100.0,
            ),
            2,
        )

    # =========================================================================
    # EVIDENCE
    # =========================================================================

    def _build_evidence(
        self,
        group: list[SwingPoint],
        touches: int,
        price: float,
        dispersion: float,
    ) -> list[str]:
        """
        Build explainable evidence for the liquidity level.
        """

        evidence = [
            f"{touches} aligned swing lows",
            f"Representative price: {price}",
            f"Price dispersion: {dispersion}",
            (
                "Equal-low tolerance: "
                f"{LIQUIDITY_TOLERANCE}"
            ),
        ]

        if touches >= 3:

            evidence.append(
                "Multiple swing confirmations detected"
            )

        if touches >= 4:

            evidence.append(
                "High-density sell-side liquidity pool"
            )

        if dispersion == 0:

            evidence.append(
                "Perfect swing-low alignment"
            )

        return evidence

    # =========================================================================
    # DEDUPLICATION
    # =========================================================================

    def _deduplicate(
        self,
        liquidity: list[LiquidityObject],
    ) -> list[LiquidityObject]:
        """
        Remove duplicate liquidity objects that resolve to
        effectively identical price levels.
        """

        if len(liquidity) <= 1:
            return liquidity

        unique: list[LiquidityObject] = []

        for level in liquidity:

            duplicate = False

            for index, existing in enumerate(
                unique
            ):

                if abs(
                    level.price
                    - existing.price
                ) <= LIQUIDITY_TOLERANCE:

                    duplicate = True

                    # ---------------------------------------------------------
                    # Preserve the stronger detection.
                    # ---------------------------------------------------------

                    if (
                        level.confidence
                        > existing.confidence
                    ):

                        unique[index] = level

                    break

            if not duplicate:

                unique.append(
                    level
                )

        return unique